---
- hosts: all
  tasks:
    - name: Add helm repo
      community.kubernetes.helm_repository:
        name: nginx
        repo_url: "https://nhungdothi155.github.io/cicd-mock-project/charts"
    - name: Install helm chart
      community.kubernetes.helm:
        name: nginx-server
        namespace: thidonhung
        chart_ref: nginx/nginx
    - name: Gather information about nginx-server
      community.kubernetes.helm_info:
        name: nginx-server
        release_namespace: thidonhung