---
- hosts: localhost
  tasks:
    - name: Install AWS CLI
      ansible.builtin.package:
        name: awscli
        state: present

    - name: Configure AWS credentials
      ansible.builtin.shell:
        cmd: |
          aws configure set aws_access_key_id {{ aws_access_key_id }}
          aws configure set aws_secret_access_key {{ aws_secret_access_key }}
          aws configure set default.region {{ region }}

    - name: Configure Kubernetes context
      command: aws eks update-kubeconfig --region {{ region }} --name {{ cluster_name }} 

    - name: Add Helm repository using command line
      ansible.builtin.shell:
        cmd: helm repo add nginx https://nhungdothi155.github.io/cicd-mock-project/charts
      args:
        executable: /bin/bash
    - name: Delete the previous repo 
      ansible.builtin.shell:
        cmd: helm delete nginx --namespace thidonhung
      args:
        executable: /bin/bash
    - name: Update Helm repository
      ansible.builtin.shell:
        cmd: helm repo update
      args:
        executable: /bin/bash
  
    - name: Install Helm chart using command line
      ansible.builtin.shell:
        cmd: helm install nginx nginx/nginx --namespace thidonhung --create-namespace --wait
      args:
        executable: /bin/bash