---
- hosts: localhost
  tasks:
    - name: Add helm repo
      community.kubernetes.helm_repository:
        name: nginx
        repo_url: "https://nhungdothi155.github.io/cicd-mock-project/charts"
    - name: List kubeconfig directory
      ansible.builtin.command:
        cmd: ls -la /home/ubuntu/.kube/
      register: ls_output

    - name: Show list output
      ansible.builtin.debug:
        msg: "{{ ls_output.stdout }}"
    - name: Install helm chart
      community.kubernetes.helm:
        kubeconfig: "/home/ubuntu/.kube/config"
        name: "nginx"
        chart_ref: "nginx/nginx"
        release_namespace: "thidonhung"
        create_namespace: true
        wait: true
        state: present
    - name: Gather information about nginx-server
      community.kubernetes.helm_info:
        name: nginx-server
        release_namespace: thidonhung