---
- hosts: server
  
  remote_user: ubuntu
  become: yes
  
  tasks:
    - name: Install AWS CLI
      ansible.builtin.package:
        name: awscli
        state: present
  
    - name: Configure AWS CLI
      ansible.builtin.shell:
        cmd: | 
          aws configure set aws_access_key_id {{AWS_ACCESS_KEY_ID}}
          aws configure set aws_secret_access_key {{AWS_SECRET_ACCESS_KEY}} 
          aws configure set region {{AWS_DEFAULT_REGION}} 
      args:
        executable: /bin/bash
   
    - name: Configure aws cluster
      ansible.builtin.shell:
        cmd : aws eks update-kubeconfig --name {{EKS_CLUSTER_NAME}} --region {{AWS_DEFAULT_REGION}}
      args:
        executable: /bin/bash
    - name: Add Helm repository using command line
      ansible.builtin.shell:
        cmd: helm repo add nginx https://nhungdothi155.github.io/CICD-Jenkins-Docker-Ansible-EKS/charts
      args:
        executable: /bin/bash
        
    - name: Update Helm repository
      ansible.builtin.shell:
        cmd: helm repo update
      args:
        executable: /bin/bash

    - name: Echo helm list
      ansible.builtin.shell:
          cmd: helm list 
      args:
        executable: /bin/bash
           
    - name: Install or upgrade Helm release
      community.kubernetes.helm:
        name: nginx
        chart_ref: nginx/nginx
        release_namespace: thidonhung-prod
        create_namespace: true
        values_files:
        - /home/ubuntu/helm/values/values-prod.yaml
        wait: true
        wait_timeout: 15m