---
- hosts: localhost
  tasks:
    - name: Configure aws 
      ansible.builtin.shell:
        cmd : aws eks update-kubeconfig --name {{EKS_CLUSTER_NAME}} --region {{AWS_DEFAULT_REGION}}
      args:
        executable: /bin/bash
    - name: Add Helm repository using command line
      ansible.builtin.shell:
        cmd: helm repo add nginx https://nhungdothi155.github.io/CICD-Jenkins-Docker-Ansible-EKS/charts
      args:
        executable: /bin/bash
        
    - name: Update Helm repository
      ansible.builtin.shell:
        cmd: helm repo update
      args:
        executable: /bin/bash

    - name: Echo helm list
      ansible.builtin.shell:
          cmd: helm list 
      args:
        executable: /bin/bash
           

    - name: Install or upgrade Helm release
      community.kubernetes.helm:
        name: nginx
        chart_ref: nginx/nginx
        release_namespace: thidonhung-prod
        create_namespace: true
