apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}
  namespace: {{ .Values.namespace}}
  labels: {{ include "nginx.labels" . | indent 4}}
spec:
  # modify replicas according to your case
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ include "nginx.labels" . | indent 6}}
  template:
    metadata:
      labels: {{include "nginx.labels" . | indent 8}}
    spec:
      containers:
      - name: {{ .Release.Name}}
        image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      imagePullSecrets:
      - name: {{ .Values.dockerSecret}} 
      nodeSelector: {{include "nodeSelector.labels" . | indent 8}}

