apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  labels: {{ include "nginx.labels" . | indent 4}}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host}}
    http:
      paths:
      - pathType: {{ .Values.ingress.http.paths.pathType}}
        path: {{ .Values.ingress.http.paths.path}}
        backend:
          service:
            name: {{ .Values.ingress.http.paths.backend.service.name}}
            port:
              number: {{ .Values.ingress.http.paths.backend.service.port}}