#define variable of values should be cammel case
replicaCount: 1
namespace: thidonhung-dev
image:
  repository: nhungdt/nginx
  tag: latest
  pullPolicy: Always
labels:
 app: nginx 
service:
  metadata:
    name: nginx-service-dev
  spec:
    type: LoadBalancer
    port: 80
    targetPort: 80
    name: http
    protocal: TCP
env: thidonhung
dockerSecret: docker-secret
nodeSelector: 
  labelName: thidonhung
  labelValue: dev

ingress:
  host: thidonhung-dev.devopsjanuary.com
  className: nginx-ingress-dev
  name: ingress-dev
  http:
    paths:
      pathType: Prefix
      path: /
      backend:
        service:
          name: nginx-service
          port: 80