apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.metadata.name}}
spec:
  type: {{ .Values.service.spec.type}}
  ports:
  - port: {{ .Values.service.spec.port }}
    targetPort: {{ .Values.service.spec.targetPort }}
    protocol: {{ .Values.service.spec.protocal}}
    name: {{ .Values.service.spec.name }}
  selector: {{ include "nginx.labels" . | indent 4 }}