#define variable of values should be cammel case
replicaCount: 4
image: nginx:1.25.4
labels:
 app: nginx 
 env: dev
service:
  metadata:
    name: nginx-service
  spec:
    type: LoadBalancer
    port: 80
    targetPort: 80
    name: http
    protocal: TCP
